stages:
  - build
  - repack

build-packages:
  image:
    name: openwrtorg/sdk:ramips-mt7621-19.07-SNAPSHOT
  stage: build
  script:
    - cd /home/build/openwrt
    - echo $USIGN_SECRET | base64 -d > key-build
    - echo "src-link taoluyun $CI_PROJECT_DIR" >> feeds.conf.default
    - ./scripts/feeds update -a
    - ./scripts/feeds install -a -p taoluyun
    - make defconfig
    - make -j1
    - mv bin $CI_PROJECT_DIR
  artifacts:
    paths:
      - bin/packages/mipsel_24kc/taoluyun

build-firmware:
  image:
    name: openwrtorg/imagebuilder:ramips-mt7621-19.07-SNAPSHOT
  stage: repack
  script:
    - cd /home/build/openwrt
    - sed "3a src taoluyun file://$CI_PROJECT_DIR/bin/packages/mipsel_24kc/taoluyun" -i repositories.conf
    - mkdir -p files/etc/dnsmasq.d
    - curl -sLf https://github.com/cokebar/gfwlist2dnsmasq/raw/master/gfwlist2dnsmasq.sh | bash -s -- -p 5300 -s ss_spsce_dst_fw --extra-domain-file $CI_PROJECT_DIR/extra-domain-list.txt -o ./files/etc/dnsmasq.d/dnsmasq_gfwlist_ipset.conf
    - make image PROFILE="mikrotik_rb750gr3" PACKAGES="block-mount dnsmasq-full dosfstools ipset iptables-mod-tproxy kmod-fs-ext4 kmod-fs-vfat kmod-tcp-bbr kmod-usb2 kmod-usb-storage luci-app-dns-forwarder luci-app-shadowsocks luci-app-sqm luci-app-upnp luci-nginx shadowsocks-libev -dnsmasq -kmod-usb3" FILES=files/
    - mv bin/targets $CI_PROJECT_DIR/bin
  artifacts:
    paths:
      - bin/targets/ramips/mt7621